### ISSUE TITLE
Update Destroyed Server Map

### ISSUE THREAD

**Issue by GhostParticle** [Mydayyy/Valheim-ServerSideMap#37] opened 2021-04-19 22:55 UTC
Really not sure if this is a game issue or a mod issue. With the new update, i have updated both client and server. I did not think that it would cause issues with this mod since the updates had nothing to do with the maps, but somehow all markers from my game have completely erased. It almost looks like it returned to an old instance of the map from the game as far as the markers go. All of my own markers disappeared which makes me wonder if this is a game glitch. The map as far as discovered area being uncovered is still, there, just the markers are gone. If you have any insight as to what to look for to assist with troubleshooting i would be happy to provide anything you need. I went through the logs and both client and server are running with matching config files. 
1: Client Side Logs
2: Server Side Logs
[LogOutput.log](https://github.com/Mydayyy/Valheim-ServerSideMap/files/6339509/LogOutput.log)
[LogOutput.log](https://github.com/Mydayyy/Valheim-ServerSideMap/files/6339512/LogOutput.log)

**Comment by Mydayyy** [comment] 2021-04-19 23:06
Greetings,

I am already investigating the update breaking the mod.

In addition to those 2 logs - could you uppload your .mod.serversidemap.explored file which you'll find along the world save?

That file includes your exploration progress as well as the pin markers.

Best Regards
Mydayyy

**Comment by GhostParticle** [comment] 2021-04-19 23:38
Is this the file you need, if not let me know. Thank You

**Had to upload in .zip file as it would not let me upload the type of file. If it doesn't unpack correctly let me know and ill repack it.**


[ServerMap.zip](https://github.com/Mydayyy/Valheim-ServerSideMap/files/6339625/ServerMap.zip)

**Comment by Mydayyy** [comment] 2021-04-20 00:09
Greetings,

could you test one thing:

Remove the SimpleRecycling Mod and try again?

Cheers

**Comment by GhostParticle** [comment] 2021-04-20 00:40
I did remove the other mod (client and server side)  and restarted the server and retried, same issue, FYI.

I checked both configs and ill post them as well.
[Configs.zip](https://github.com/Mydayyy/Valheim-ServerSideMap/files/6339793/Configs.zip)

**Comment by Mydayyy** [comment] 2021-04-20 00:46
Sorry for all those questions, I am trying to reproduce the issue but so far I have failed. Your map seems to work with my client.

One other interesting question to try to locate it further:

Inside your server log, the last logged connected player was at [Info   : Unity Log] 04/18/2021 10:39:52:

while inside your client log the most recent connection is from [Info   : Unity Log] 04/19/2021 17:31:58

Could it be that there is something missing from the server log? I am trying to see whether the server still sends the pins and the client ignores them or the server does not send them at all

Best Regards

**Comment by GhostParticle** [comment] 2021-04-20 00:51
My friend may have connected late last night but i was not around for that, so its possible. I disconnected last night around 1930ish. I relogged on today for the first time at the 1731 mark. So i wonder if its not seeing my player instance on the server for some reason. Let me do some troubleshooting from my end on that and i will get back with you tomorrow, time is limited for me. If you can think of anything to look for it would be very much appreciated. I do appreciate you looking at this with me.

**Comment by Mydayyy** [comment] 2021-04-20 00:59
I appreciate that.

Well, the good news is that the map file is not corrupt and all the pins (96 if we count them) are there, just a matter of finding out why they are not send.


The two  most important lines regarding pins are:

Server log:
[Info   :ServerSideMap] Packing pins: X

Client log:
[Info   :ServerSideMap] Client received initial pin data by server. Pins: X




Depending on whether both or only one is missing we can infer whether the server is sending pins and the client ignores them, or the server does not send them at all.  For this we just need to look at the server logs from an connection attempt.

Since the latest connection attempt you made does not appear inside the server log, two reasons I can think of:
- The server never received the attempt (E.g did you accidentally connect to a local world, wrong server? Happened to me already)
- The logs from the server were not flushed to file

I'll be heading to bed now, feel free to post an update I will check back asap

Best Regards
Mydayyy

**Comment by GhostParticle** [comment] 2021-04-20 21:52
So, after digging around a bit, I decided to try a few things. 

- deleted both client and server side mod including config file, did not delete the actual map file
- re-uploaded updated version of the mod (client and server) and ran the game 
- closed out game and updated config file on client
- server side never re-created config file
- deleted both server and client mods, re-loaded game
- added both server and client mods, re-loaded game
- map still not showing and server did not create config file

at this point i'm at a loss, its almost like the server is not recognizing the mod or something
[Files.zip](https://github.com/Mydayyy/Valheim-ServerSideMap/files/6346826/Files.zip)

**Comment by Mydayyy** [comment] 2021-04-20 21:57
Greetings,

server not creating config file really sounds like the mod is just not loaded.

The server log you attached has the last entry which is 
[Info   : Unity Log] 04/19/2021 17:21:38: clone 566

Any chance you have the most recent logfile which also includes the most recent servers? Most interestingly would be to include a server starting up to see whether bepinex/ssm is still correctly loaded, I would guess it is not right now.

Cheers
Mydayyy

**Comment by GhostParticle** [comment] 2021-04-21 22:38
Well, this has been fun. If I wasn't an IT Professional I would have never gotten this fixed. The issue wasn't your mod, it was the server. I ended up nuking all of the mods including the framework and re-installing everything fresh. That didn't work off the start. Then I noticed that my worlds file had multiple .db files and I'm not sure which was breaking it, but I ended up deleting the ones I felt were not working. Good news is, I now have my map back, so that part is now working as intended. Bad news is for some reason I lost all of my current inventory, including my wishbone :-( .... I lost that before even deleting the .db files. 

So, as it stands, its working correctly again at no fault of you or your mod. Just a glitch somewhere in the instance connections of the files. I really do appreciate all of your work creating the mod and the help you have provided me during this. You can close this out now. And again, thank you very much.

**Comment by Mydayyy** [comment] 2021-04-22 09:17
Greetings,

glad you could resolve it.

One world save is represented by one .db and as well as .fwl file containing metadata about the world. So if you for example rename them incorrectly, it might be that you spawn in a world that looks exactly like your old world, but is missing any progress.

The character save and inventory is not stored on the world at all, those are clientside and live in a separate file / location. So its a bit puzzling that your character lost items while your were taking care of the world issues. In any case, if you want, there are already character/inventory editors out there that could give you your wishbone back.

In any cose, I'll be closing this here, thanks for the final update :)

Cheers
Mydayyy

**Closed by Mydayyy** 2021-04-22 09:17 UTC

**Comment by labmonkey** [comment] 2021-04-22 10:38
> Well, this has been fun. If I wasn't an IT Professional I would have never gotten this fixed. The issue wasn't your mod, it was the server. I ended up nuking all of the mods including the framework and re-installing everything fresh. That didn't work off the start. Then I noticed that my worlds file had multiple .db files and I'm not sure which was breaking it, but I ended up deleting the ones I felt were not working. Good news is, I now have my map back, so that part is now working as intended. Bad news is for some reason I lost all of my current inventory, including my wishbone :-( .... I lost that before even deleting the .db files.
> 
> So, as it stands, its working correctly again at no fault of you or your mod. Just a glitch somewhere in the instance connections of the files. I really do appreciate all of your work creating the mod and the help you have provided me during this. You can close this out now. And again, thank you very much.

@GhostParticle As I am having same issue could you tell me what did you do exactly in the server? Did you delete all the .db files but left only the most recent one? Is that all? And then when you logged you had your world with whole progress and the pins started working again? (Not asking here about that your character lost items because I suppose thats a different issue)

**Comment by GhostParticle** [comment] 2021-04-22 11:35
@labmonkey , Check the file dates before deleting any, make sure you use one that is close to the date you want. Mine had about 6 different files, some had .old and .new next to them, I ended up deleting all but the original because it had the most MBs and correct date. Once i did that i spun up the server and it ended up creating another .db file that i had to go and re-delete. Just make sure you save the files first before deletion just in case. If you delete all the files to let it re-create it will lose all progress in the world so make sure you keep at least 1 .db file and 1 .fwl file. But once i got to a point where it had only 1 .db and 1 .fwl file while it was running, all the map pins seemed to come back. Hopefully this helps. Let me know if you have any more questions.

**Comment by Mydayyy** [comment] 2021-04-22 11:38
Might want to just simply zip the entire save folder as a backup before proceeding, just as a safety measure

Cheers
Mydayyy

**Comment by labmonkey** [comment] 2021-04-23 17:50
Actually what I did was to stop the server, move all those .db and .fwl files away to another directory besides the most recent one, start thbe server (it recreated some), stop the server again and override those files with those I just moved away, start the server. So it seems that server has rebuilt something while those files were away.

**Comment by labmonkey** [comment] 2021-04-27 05:52
@GhostParticle Did this issue happen to you again? Because for me after deleting and replacing files it actually happened again some time later. If it did not happen to you then maybe I should just delete and not replace them...

**Comment by GhostParticle** [comment] 2021-04-27 21:33
> @GhostParticle Did this issue happen to you again? Because for me after deleting and replacing files it actually happened again some time later. If it did not happen to you then maybe I should just delete and not replace them just like you did...

I have not had any additional issues since the original. But yes i deleted unused .db and .fwl files completely and only kept the ones i knew were the ones i wanted.
