### ISSUE TITLE
ServerSideMap fails to sync in the presence of the RRRCore mod

### ISSUE THREAD

**Issue by thecsapprentice** [Mydayyy/Valheim-ServerSideMap#43] opened 2021-07-21 06:45 UTC
Hi! 

I've been having some trouble getting my server's mods set up, in particular ServerSideMap. After some experimentation today, I was able to confirm that the trouble seems to arise from including the RRRCore mod (https://valheim.thunderstore.io/package/neurodr0me/RRRCore/).

The server logs don't seem to indicate any errors happening, but the client is a different story. I get an ugly looking traceback in the logs when it, presumably, tries to sync. This ultimately fails for some reason and the map on the client is not updated, though otherwise the game appears unaffected by the error.

I'd love to get both of these working together at some point, and hopefully the logs provided help with that. Please let me know if I can provide any additional information.

Server Log:
https://gist.github.com/thecsapprentice/ba00963be44f87f9187c1db512f74bf2

Client Log (Error around line 709):
https://gist.github.com/thecsapprentice/00624e09f4724ffabc65d050dccfcc64

**Comment by Mydayyy** [comment] 2021-07-21 18:14
Greetings,

I hope you had a pleasant day.

From the pure look at the clientlogs, this issue could very well be the one I may have fixed in an earlier release candidate. Unfortunately, I do have a few unreleased versions of SSM lying on Github here which never got released due to a lack of testing.

Can you try the following:
- Please back up your current pins (back up your character file. Seems like you don't have serverside pins yet, if you have - back them up too.
- I had one report of missing pins on RC 1.3.4, which I never was able to reproduce - better be safe than sorry.
- Install RC 1.3.4 => https://github.com/Mydayyy/Valheim-ServerSideMap/releases/download/rc-1.3.4/ServerSideMap.zip
- Try again

This RC contains an earlier bugfix regarding Better Continents which might help with RRRCore too.

Best Regards
Mydayyy

**Comment by thecsapprentice** [comment] 2021-07-21 19:25
Mydayyy,

Awesome! This seems to have solved the issue for moment! Maps appear to be syncing properly again, though I haven't tested pins yet. I'll need to do more work and see if integrating the full stack of mods breaks stuff again, but I'm hopeful it will be stable overall. 

I'm guessing the changes in the RC have something to do with network code that conflicts with other mods, like RRRCore or BetterWorlds? Hopefully this will get a chance to migrate to the next official release soon!

Thanks!

**Comment by Mydayyy** [comment] 2021-07-23 23:48
Hey,

> I'm guessing the changes in the RC have something to do with network code that conflicts with other mods, like RRRCore or BetterWorlds? Hopefully this will get a chance to migrate to the next official release soon!

I was running into a race condition to be exact. Accessing a variable which was (usually) available. Certain mods which add some networking (e.g extend the handshake) delayed the initialization of that variable - meaning I had to wait for that.

> Awesome! This seems to have solved the issue for moment! Maps appear to be syncing properly again, though I haven't tested pins yet. I'll need to do more work and see if integrating the full stack of mods breaks stuff again, but I'm hopeful it will be stable overall.

Apart from the one report which unfortunately, I never was able to reproduce in practice or in theory - the RC should be fully functional, I tested it and everything worked.

Best Regards
Mydayyy

**Comment by Mydayyy** [comment] 2021-09-19 00:35
Went live in 1.3.5

**Closed by Mydayyy** 2021-09-19 00:35 UTC
